### ISSUE TITLE
Upgrade Repo - High Level Task

### ISSUE THREAD

**Issue by danny-people-plus** [StafflinePeoplePlus/peopleplus-template#245]
Look at the Videos https://github.com/StafflinePeoplePlus/videos and LearningPlus Shop https://github.com/StafflinePeoplePlus/learning-plus-shop repos and bring this in line for packages and CD/CI.

**Comment by jamesbirtles** [comment]
Things to look at:
- eslint
- prettier
- zap
- a11y (done via playwright test)
- playwright
